name: clientepro
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cool_alert: ^2.0.1
  provider: ^6.1.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  vocsy_epub_viewer: ^2.0.0
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  mobx: ^2.2.3
  flutter_mobx: ^2.2.0+1
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  introduction_screen: ^3.1.11
  badges: ^3.1.2

flutter_native_splash:
  color: "#FFA726"
  image: "assets/logo.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  remove_alpha_ios: true
  android: "ic_launcher"
  adaptive_icon_background: "#FFA726"
  adaptive_icon_foreground: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/img_error.png
    - assets/img_capa.jpg
    - assets/interesses/
    - assets/icons/
